name: 2222222222
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      tags2222:
        description: 'Test scenario tags'
        required: true
        type: number
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - run : echo Create annotation for build error
  
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  test3:
    runs-on: ubuntu-latest
    steps:
      - run: echo 3

  test4:
    needs: test2
    runs-on: ubuntu-latest
    steps:
      - run: echo 4


  test5:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 20

