name: 2222222222
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create annotation for build error
      run: echo "::error file=app.js,line=1::Missing semicolon"
    - run: echo "::debug::Set the Octocat variable"
    - run: echo "::warning file=app.js,line=1,col=5,endColumn=7::Missing semicolon"

    - run: echo "::error file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
    - name: Group of log lines
      run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"      
    - run: echo "::notice file=app.js,line=1,col=5,endColumn=7::Missing semicolon"
    - run: echo "::add-mask::Mona The Octocat"
    - run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY



